services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GO_VERSION: ${GO_VERSION-1.25}
        BUILD_HASH: ${BUILD_HASH-dev}
    image: iwvw/halowebui:${WEBUI_DOCKER_TAG-latest}
    container_name: open-webui
    volumes:
      - open-webui:/app/data
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'WEBUI_SECRET_KEY='
      - 'HALO_GO_MEMORY_LIMIT_MIB=48'
      - 'ENABLE_LOCAL_MODEL_RUNTIME=false'
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}
