name: Go backend CI

on:
  push:
    branches:
      - main
      - dev
    paths:
      - 'backend-go/**'
  pull_request:
    branches:
      - main
      - dev
    paths:
      - 'backend-go/**'

jobs:
  build:
    name: 'Test Go backend'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: backend-go/go.mod
      - name: Check formatting
        working-directory: backend-go
        shell: bash
        run: test -z "$(gofmt -l .)"
      - name: Test
        working-directory: backend-go
        run: go test ./...
